import { PERMISSIONS, Permission } from './permission.constants';

const ROLES = {
  ADMIN: 'Admin',
  STAFF: 'Staff',
  RESIDENT: 'Resident',
  ELECTRICIAN: 'Electrician',
  SECURITY: 'Security',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

const ACTIONS = {
  VIEW: 'view',
  EDIT: 'edit',
  DELETE: 'delete',
  PERMISSION: 'permission',
  AVAILABILITY: 'availability',
} as const;

export type ActionType = (typeof ACTIONS)[keyof typeof ACTIONS];

const ROUTES = {
  DASHBOARD: '/dashboard',
  RESIDENTS: '/residents',
  VISITORS: '/visitors',
  COMPLAINTS: '/complaints',
  MAINTENANCE: '/maintenance',
  AMENITIES: '/amenities',
  BOOKINGS: '/bookings',
  STAFF: '/staff',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  OTP_VERIFICATION: '/otp-verification',
  ADMIN_COMPLAINTS: '/admin/complaints',
  ADMIN_AMENITIES: '/admin/amenities',
  ADMIN_STAFF: '/admin/staff',
  STAFF_COMPLAINTS: '/staff/complaints',
  REPORTS: '/reports',
  MANAGE_PERMISSIONS: '/manage-permissions',
  USER_MANAGEMENT: '/user-management',
  SECURITY_BOOK_VISITOR: '/security/book-visitor',
  SECURITY_SCAN: '/security/scan',
  SECURITY_VISITORS: '/security/visitors',
} as const;

const ICONS = {
  DASHBOARD: 'dashboard',
  RESIDENTS: 'groups',
  VISITORS: 'badge',
  COMPLAINTS: 'report_problem',
  MAINTENANCE: 'build',
  AMENITIES: 'pool',
  BOOKINGS: 'event',
  STAFF: 'engineering',
  SETTINGS: 'settings',
  NOTIFICATIONS: 'notifications',
  SEARCH: 'search',
  FILTER: 'filter_list',
  CLOSE: 'close',
  MORE: 'more_vert',
  ADD: 'add',
  EDIT: 'edit',
  DELETE: 'delete',
  PROFILE: 'account_circle',
  LOGOUT: 'logout',
  INBOX: 'inbox',
  WARNING: 'warning',
  HELP: 'help',
  CHECK: 'check_circle',
  ASSIGN: 'person_add',
  REPORT: 'bar_chart',
  COMMENT: 'comment',
  QR_CODE: 'qr_code_scanner',

  ESCALATION: 'report_problem',
  ACCEPT: 'check_circle',
  DENY: 'cancel',
  REASSIGN: 'swap_horiz',
  PHONE: 'call',
  PERSON: 'person',
  CATEGORY: 'category',
  DESCRIPTION: 'description',
  OPEN_IN_NEW: 'open_in_new',
  ARROW_UPWARD: 'arrow_upward',
  ARROW_DOWNWARD: 'arrow_downward',

  BRAND: 'apartment',
  BACK: 'arrow_back',
  PREV: 'chevron_left',
  NEXT: 'chevron_right',

  AVAILABILITY: 'event_available',
  TIME_SLOT: 'schedule',
  DONE_ALL: 'done_all',
  DELETE_SWEEP: 'delete_sweep',
  STAR: 'star',
  STAR_OUTLINE: 'star_outline',
  SEND: 'send',
  SYNC: 'sync',
  APPROVAL: 'fact_check',
} as const;

const STATUS = {
  CONFIRMED: 'Confirmed',
  PENDING: 'Pending',
  RESOLVED: 'Resolved',
  OPEN: 'Open',
  IN_PROGRESS: 'In Progress',
  CANCELLED: 'Cancelled',
  REJECTED: 'Rejected',
  APPROVED: 'Approved',
} as const;

export type StatusType = (typeof STATUS)[keyof typeof STATUS];

export type StatusColorKey = 'success' | 'warning' | 'danger' | 'info' | 'neutral';

const STATUS_COLOR_KEY: Record<string, StatusColorKey> = {
  [STATUS.CONFIRMED]: 'success',
  [STATUS.RESOLVED]: 'success',
  [STATUS.APPROVED]: 'success',
  [STATUS.PENDING]: 'warning',
  [STATUS.IN_PROGRESS]: 'warning',
  [STATUS.OPEN]: 'info',
  [STATUS.CANCELLED]: 'neutral',
  [STATUS.REJECTED]: 'danger',
  Active: 'success',
  Completed: 'success',
};

const COMPLAINT_STATUS = {
  OPEN: 'Open',
  ASSIGNED: 'Assigned',
  IN_PROGRESS: 'InProgress',
  RESOLVED: 'Resolved',
  CLOSED: 'Closed',
  CANCELLED: 'Cancelled',
  ESCALATED: 'Escalated',
} as const;

export type ComplaintStatusType = (typeof COMPLAINT_STATUS)[keyof typeof COMPLAINT_STATUS];

const COMPLAINT_STATUS_COLOR_KEY: Record<string, StatusColorKey> = {
  [COMPLAINT_STATUS.OPEN]: 'info',
  [COMPLAINT_STATUS.ASSIGNED]: 'warning',
  [COMPLAINT_STATUS.IN_PROGRESS]: 'warning',
  'In Progress': 'warning',
  [COMPLAINT_STATUS.RESOLVED]: 'success',
  [COMPLAINT_STATUS.CLOSED]: 'success',
  [COMPLAINT_STATUS.CANCELLED]: 'neutral',
  [COMPLAINT_STATUS.ESCALATED]: 'danger',
};

const ASSIGNMENT_STATUS_COLOR_KEY: Record<string, StatusColorKey> = {
  Pending: 'warning',
  Accepted: 'success',
  Denied: 'danger',
  Reassigned: 'warning',
};

const VISIT_STATUS_COLOR_KEY: Record<string, StatusColorKey> = {
  'Checked In': 'success',
  'Checked Out': 'success',
  Expired: 'danger',
};

Object.assign(
  STATUS_COLOR_KEY,
  COMPLAINT_STATUS_COLOR_KEY,
  ASSIGNMENT_STATUS_COLOR_KEY,
  VISIT_STATUS_COLOR_KEY,
);

const DASHBOARD_VIEW = {
  ADMIN: 'admin',
  STAFF: 'staff',
  RESIDENT: 'resident',
} as const;

const ACCENT = {
  PRIMARY: 'primary',
  DANGER: 'danger',
  INFO: 'info',
  SUCCESS: 'success',
} as const;

const CATEGORIES = {
  PLUMBING: 'Plumbing',
  ELECTRICAL: 'Electrical',
  SECURITY: 'Security',
  HOUSEKEEPING: 'Housekeeping',
  LIST: ['Plumbing', 'Electrical', 'Security', 'Housekeeping'] as string[],
} as const;

const SENTINELS = {
  DUMMY_GUID: '00000000-0000-0000-0000-000000000000',
} as const;

const HTTP = {
  TIMEOUT: 15000,
  AUTH_HEADER_PREFIX: 'Bearer ',
} as const;

const VALIDATION = {
  EMAIL_PATTERN: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
  PASSWORD_PATTERN: /^(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]).{8,15}$/,
  PHONE_PATTERN: /^\d{10}$/,
} as const;

const DIALOG_WIDTHS = {
  SMALL: '420px',
  MEDIUM: '480px',
  LARGE: '520px',
  XLARGE: '600px',
} as const;

const PAGINATION = {
  DEFAULT_PAGE_SIZE: 10,
  DEFAULT_PAGE: 1,
  USER_LIST_LIMIT: 100,
  PAGE_SIZE_OPTIONS: [5, 10, 20, 50] as number[],
  NOTIFICATION_PAGE_LIMIT: 50,
};

const STRINGS = {
  APP_NAME: 'Lumina Community',
  WELCOME_BACK: 'Welcome back',
  SEARCH_PLACEHOLDER: 'Search residents, units, or logs...',
  NO_DATA: 'No data available',
  LOADING: 'Loading...',
  VIEW_ALL: 'View All',
  SAVE: 'Save',
  APPROVE: 'Approve',
  REJECT: 'Deny',
  APPROVE_VISIT_TITLE: 'Approve Visit',
  APPROVE_VISIT_MESSAGE: 'Are you sure you want to approve this visit?',
  REJECT_VISIT_TITLE: 'Reject Visit',
  REJECTION_REASON_LABEL: 'Reason for rejection',
  REJECTION_REASON_REQUIRED: 'A rejection reason is required.',
  VISIT_APPROVE_FAILED: 'Failed to approve visit.',
  VISIT_REJECT_FAILED: 'Failed to reject visit.',
  CANCEL: 'Cancel',
  CONFIRM: 'Confirm',
  DELETE: 'Delete',
  EDIT: 'Edit',
  ADD_NEW: 'Add New',
  CLOSE: 'Close',
  RESET: 'Reset',
  ARE_YOU_SURE: 'Are you sure?',
  ARE_YOU_SURE_MESSAGE: 'This action cannot be undone.',
  ASSIGN_STAFF: 'Assign Staff',
  WORK_STATUS: 'Work Status',
  UPDATE_STATUS: 'Update Status',
  DENY_REASON_PLACEHOLDER: 'Explain why this complaint is being denied...',
  COMMENTS: 'Comments',
  VIEW_REPORT: 'View Report',
  UNASSIGNED: 'Unassigned',
  RAISED_ON: 'Raised On',
  CATEGORY_LABEL: 'Category',
  DESCRIPTION_LABEL: 'Description',
  BOOK_UNPLANNED_VISITOR_TITLE: 'Book Unplanned Visitor',
  BLOCK_NUMBER_LABEL: 'Block Number',
  FLAT_NUMBER_LABEL: 'Flat Number',
  BLOCK_NUMBER_REQUIRED: 'Block number is required.',
  FLAT_NUMBER_REQUIRED: 'Flat number is required.',
  VISITOR_NAME_REQUIRED: 'Visitor name is required.',
  VISITOR_PHONE_INVALID: 'Enter a valid 10-digit phone number.',
  VISITOR_EMAIL_INVALID: 'Enter a valid email address.',
  VISITOR_TYPE_REQUIRED: 'Please select a visitor type.',
  PURPOSE_TYPE_REQUIRED: 'Please select a purpose.',
  SELECT_VISITOR_TYPE: 'Select type',
  SELECT_PURPOSE_TYPE: 'Select purpose',
  SELECT_BLOCK: 'Select block',
  SELECT_FLAT: 'Select flat',
  SELECT_BLOCK_FIRST: 'Select a block first',
  UNPLANNED_VISIT_SUBMITTED: 'Visitor submitted for resident approval.',
  VISITOR_TYPES_LOAD_FAILED: 'Could not load visitor types. Please try again.',
  PURPOSE_TYPES_LOAD_FAILED: 'Could not load purpose types. Please try again.',
  FLATS_LOAD_FAILED: 'Could not load blocks and flats. Please try again.',
  SCAN_VISITOR_TITLE: 'Scan Visitor QR',
  CHECK_IN: 'Check In',
  CHECK_OUT: 'Check Out',
  SCAN_CHECKIN_SUCCESS: 'Visitor checked in successfully.',
  SCAN_CHECKOUT_SUCCESS: 'Visitor checked out successfully.',
  SCAN_FAILED: 'Scan failed. Please try again.',
  CAMERA_PERMISSION_DENIED:
    'Camera access is required to scan. Please enable it in your browser settings.',

  ADD_STAFF: 'Add Staff',
  ADD_AMENITY: 'Add Amenity',
  STAFF_NAME: 'Name',
  STAFF_EMAIL: 'Email',
  STAFF_CATEGORY: 'Category',
  COMPLAINTS: 'Complaints',
  ESCALATED_COMPLAINTS: 'Escalated Complaints',
  AMENITIES: 'Amenities',
  STAFF: 'Staff',
  ACCEPT: 'Accept',
  DENY: 'Deny',
  REASSIGN_STAFF: 'Reassign Staff',
  REASON_FOR_DENIAL: 'Reason for Denial',
  RESIDENT_DETAILS: 'Resident Details',
  SELECT_STAFF: 'Select Staff',
  AMENITY_NAME: 'Amenity Name',
  AMENITY_DESCRIPTION: 'Description',
  NO_COMPLAINTS: 'No complaints found',
  NO_STAFF: 'No staff members found',
  NO_AMENITIES: 'No amenities found',
  SUBMIT: 'Submit',

  LOGOUT: 'Logout',
  SETTINGS_TITLE: 'Settings',
  TAB_PROFILE: 'Profile',
  TAB_APPEARANCE: 'Appearance',
  TAB_SECURITY: 'Security',
  APPEARANCE_THEME_TITLE: 'Theme',
  APPEARANCE_COLOR_TITLE: 'Color Palette',
  APPEARANCE_FONT_TITLE: 'Font Family',
  APPEARANCE_SAVED: 'Appearance preferences saved.',
  CURRENT_PASSWORD_LABEL: 'Current Password',
  NEW_PASSWORD_LABEL: 'New Password',
  CURRENT_PASSWORD_REQUIRED: 'Current password is required.',
  PASSWORD_MUST_DIFFER: 'New password must be different from current password.',
  CHANGE_PASSWORD_FAILED: 'Failed to change password.',
  PAGE_LABEL: 'Page',
  OF_LABEL: 'of',
  STAFF_SUFFIX: 'staff',
  PRIORITY_LABEL: 'Priority',
  STATUS_LABEL: 'Status',
  RESOLVED_LABEL: 'Resolved',
  PENDING_LABEL: 'Pending',

  DASHBOARD_SUBTITLE: 'Manage your community with efficiency.',
  DASHBOARD_URGENT_BANNER_SUBTITLE:
    'Manage your community with efficiency. You have 3 urgent maintenance requests today.',
  VISITOR_TRENDS_TITLE: 'Visitor Trends',
  LATEST_BOOKINGS_TITLE: 'Latest Bookings',
  TOTAL_RESIDENTS_LABEL: 'Total Residents',
  ACTIVE_VISITORS_LABEL: 'Active Visitors',
  OPEN_COMPLAINTS_LABEL: 'Open Complaints',
  TODAYS_BOOKINGS_LABEL: "Today's Bookings",
  AMENITY_LABEL: 'Amenity',
  RESIDENT_LABEL: 'Resident',
  UNIT_LABEL: 'Unit',
  TIME_SLOT_LABEL: 'Time Slot',
  COMPLAINTS_BY_CATEGORY: 'Complaints by Category',
  MY_COMPLAINTS_TITLE: 'My Complaints',
  RECENT_COMPLAINTS_TITLE: 'Recent Complaints',
  RESOLUTION_PERFORMANCE: 'Resolution Perf.',
  TOTAL_COMPLAINTS: 'Total Complaints',
  ASSIGNED_TO_TEAM: 'Assigned to Team',
  ESCALATED: 'Escalated',

  LOGIN_TITLE: 'Login',
  LOGIN_BUTTON: 'Login',
  LOGGING_IN: 'Logging in...',
  FORGOT_PASSWORD_LINK: 'Forgot Password?',
  NO_ACCOUNT: 'No account?',
  REGISTER_LINK: 'Register',
  EMAIL_LABEL: 'Email',
  EMAIL_REQUIRED: 'Email is required.',
  EMAIL_VALIDATION: 'Enter a valid email address (e.g., user@domain.com).',
  PASSWORD_LABEL: 'Password',
  REGISTER_TITLE: 'Register',
  REGISTERING: 'Registering...',
  USERNAME_LABEL: 'Username',
  USERNAME_VALIDATION: 'Username is required.',
  PHONE_LABEL: 'Phone',
  PHONE_REQUIRED: 'Phone is required.',
  ROLE_LABEL: 'Role',
  ROLES_LOADING: 'Loading roles...',
  ROLE_REQUIRED: 'Please select a role.',
  FLAT_LABEL: 'Flat',
  FLAT_SEARCH_PLACEHOLDER: 'Search by block (e.g. A) or number...',
  NO_FLATS_FOUND: 'No flats found',
  FLATS_LOADING: 'Loading flats...',
  FLAT_REQUIRED: 'Please select a flat.',
  PHOTO_LABEL: 'Photo (optional)',
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
  LOGIN_LINK: 'Login',
  SEND_OTP_FAILED: 'Failed to send OTP. Please try again.',
  INVALID_OTP: 'Invalid OTP. Please try again.',
  PASSWORDS_MISMATCH: 'Passwords do not match.',
  RESET_PASSWORD_FAILED: 'Failed to reset password. Please try again.',

  FORGOT_PASSWORD_TITLE: 'Forgot Password',
  PHONE_NUMBER: 'Phone Number',
  PHONE_PREFIX: '+91',
  PHONE_PLACEHOLDER: '9879879870',
  PHONE_VALIDATION: 'Enter a valid 10-digit phone number.',
  SEND_OTP: 'Send OTP',
  SENDING: 'Sending...',
  BACK_TO_LOGIN: 'Back to Login',
  ENTER_OTP_TITLE: 'Enter OTP',
  OTP_SENT_PREFIX: 'OTP sent to',
  OTP_LABEL: 'OTP',
  OTP_PLACEHOLDER: '556272',
  OTP_VALIDATION: 'Enter a valid 6-digit OTP.',
  VERIFY_OTP: 'Verify OTP',
  VERIFYING: 'Verifying...',
  RESET_PASSWORD_TITLE: 'Reset Password',
  NEW_PASSWORD: 'New Password',
  PASSWORD_REQUIRED: 'Password is required.',
  PASSWORD_VALIDATION:
    'Password must be 8-15 characters with at least 1 uppercase letter, 1 digit, and 1 special character.',
  CONFIRM_PASSWORD: 'Confirm Password',
  CONFIRM_PASSWORD_REQUIRED: 'Confirm password is required.',
  RESETTING: 'Resetting...',

  MANAGE_PERMISSIONS_TITLE: 'Manage Permissions',
  PERMISSIONS_UPDATED: 'Permissions updated successfully.',
  FAILED_TO_LOAD_PERMISSIONS: 'Failed to load permissions.',
  FAILED_TO_UPDATE_PERMISSIONS: 'Failed to update permissions.',
  SELECT_USER_TO_MANAGE: 'Search and select a user to manage their permissions.',
  SEARCH_USERS_PLACEHOLDER: 'Search users by name...',
  SEARCHING: 'Searching...',
  SAVING: 'Saving...',
  UPDATE_PERMISSIONS: 'Update Permissions',
  FAILED_TO_LOAD_ROLES: 'Failed to load roles.',
  FAILED_TO_LOAD_CATEGORIES: 'Failed to load categories.',
  REQUIRED_FIELDS: 'Please fill in all required fields.',
  FAILED_TO_UPLOAD_IMAGE: 'Failed to upload image.',
  FAILED_TO_LOAD_USER_DETAILS: 'Failed to load user details.',
  CHANGE_PHOTO: 'Change',
  NAME_PLACEHOLDER: 'John Doe',
  EMAIL_PLACEHOLDER: 'john@example.com',
  PASSWORD_PLACEHOLDER: 'Min 6 characters',
  USER_MANAGEMENT_TITLE: 'User Management',
  ADD_USER: 'Add User',
  EDIT_USER: 'Edit User',
  DELETE_USER: 'Delete User',
  UPDATE_USER_PERMISSION: 'Update Permission',
  USER_ADDED_SUCCESS: 'User added successfully.',
  USER_UPDATED_SUCCESS: 'User updated successfully.',
  USER_DELETED_SUCCESS: 'User deleted successfully.',
  FAILED_TO_LOAD_USERS: 'Failed to load users.',
  FAILED_TO_ADD_USER: 'Failed to add user.',
  FAILED_TO_UPDATE_USER: 'Failed to update user.',
  FAILED_TO_DELETE_USER: 'Failed to delete user.',
  DELETE_USER_CONFIRM: 'Are you sure you want to delete this user?',
  SELECT_ROLE: 'Select Role',
  ROLE_STAFF: 'Staff',
  ROLE_SECURITY: 'Security',
  SELECT_CATEGORY: 'Select Category',
  LOADING_CATEGORIES: 'Loading categories...',
  UPLOADING: 'Uploading...',
  NO_USERS_FOUND: 'No users found.',
  ACTIONS: 'Actions',
  VIEW_USER: 'View',
  SEARCH_USER_PLACEHOLDER: 'Search by name...',
  FILTER_BY_ROLE: 'All Roles',
  SORT_NAME: 'Sort by Name',
  SORT_ASC: 'A-Z',
  SORT_DESC: 'Z-A',
  ITEMS_PER_PAGE: 'Items per page',
  USER_DETAIL_TITLE: 'User Details',
  USER_STATUS_ACTIVE: 'Active',
  USER_STATUS_INACTIVE: 'Inactive',
  CREATED_AT_LABEL: 'Created At',
  FLAT_ID_LABEL: 'Flat',
  FLAT_BLOCK_LABEL: 'Block',
  FLAT_FLOOR_LABEL: 'Floor',
  AVAILABILITY: 'Availability',
  PHOTO_URL_LABEL: 'Photo',

  BOOK_VISITOR: 'Book Visitor',
  MY_VISITS_TITLE: 'My Visitors',
  UPCOMING_VISITS_TAB: 'Upcoming',
  VISIT_HISTORY_TAB: 'History',
  NO_VISITS_UPCOMING: 'No upcoming visits',
  NO_VISITS_HISTORY: 'No visit history',
  VISITOR_NAME_LABEL: 'Visitor Name',
  VISITOR_PHONE_LABEL: 'Phone Number',
  VISITOR_EMAIL_LABEL: 'Email (optional)',
  VISITOR_TYPE_LABEL: 'Visitor Type',
  PURPOSE_TYPE_LABEL: 'Purpose',
  START_DATE_LABEL: 'Start Date',
  END_DATE_LABEL: 'End Date',
  VISIT_BOOKED_SUCCESS: 'Visit booked successfully.',
  VISIT_BOOK_FAILED: 'Failed to book the visit. Please try again.',
  VISIT_UPDATED_SUCCESS: 'Visit updated successfully.',
  VISIT_UPDATE_FAILED: 'Failed to update the visit.',
  CANCEL_VISIT_TITLE: 'Cancel Visit',
  CANCEL_VISIT_MESSAGE: 'Are you sure you want to cancel this visit? This action cannot be undone.',
  VISIT_CANCELLED_SUCCESS: 'Visit cancelled successfully.',
  VISIT_CANCEL_FAILED: 'Failed to cancel the visit.',
  VISITS_LOAD_FAILED: 'Failed to load visits.',
  QR_SENT_LABEL: 'QR code sent to visitor email',
  UPDATE: 'Update',
  UPDATE_VISITOR_TITLE: 'Update Visitor',

  VISITOR_UPDATE_FAILED: 'Failed to update visitor.',

  NOTIFICATIONS_TITLE: 'Notifications',
  MARK_ALL_READ: 'Mark all as read',
  DELETE_ALL: 'Delete all',
  NO_NOTIFICATIONS: 'No notifications',
  NOTIFICATION_VIEW: 'View',
  LOGIN_SUCCESS: 'Login successful!',

  APPROVALS_TITLE: 'Approvals',
  NO_PENDING_APPROVALS: 'No pending approvals',
  USER_APPROVED_SUCCESS: 'User has been approved successfully.',
  FAILED_TO_APPROVE_USER: 'Failed to approve user.',
} as const;

export interface NavItem {
  label: string;
  icon: string;
  route: string;
  roles: Role[];
  permissions?: Permission[];
}

const NAV_ITEMS: NavItem[] = [
  {
    label: 'Dashboard',
    icon: ICONS.DASHBOARD,
    route: ROUTES.DASHBOARD,
    roles: [ROLES.ADMIN, ROLES.STAFF, ROLES.RESIDENT, ROLES.ELECTRICIAN, ROLES.SECURITY],
  },
  {
    label: 'Book Unplanned Visitor',
    icon: ICONS.ADD,
    route: ROUTES.SECURITY_BOOK_VISITOR,
    roles: [ROLES.SECURITY],
    permissions: [PERMISSIONS.VISIT_REGISTER],
  },
  {
    label: 'Scan Visitor',
    icon: ICONS.QR_CODE,
    route: ROUTES.SECURITY_SCAN,
    roles: [ROLES.SECURITY],
    permissions: [PERMISSIONS.VISIT_CHECKIN],
  },
  {
    label: 'Flats',
    icon: ICONS.VISITORS,
    route: ROUTES.SECURITY_VISITORS,
    roles: [ROLES.SECURITY, ROLES.ADMIN],
    permissions: [PERMISSIONS.JOB_TRIGGER],
  },
  {
    label: 'User Management',
    icon: ICONS.PERSON,
    route: ROUTES.USER_MANAGEMENT,
    roles: [ROLES.ADMIN],
    permissions: [PERMISSIONS.USER_MANAGE],
  },
  {
    label: 'Visitors',
    icon: ICONS.VISITORS,
    route: ROUTES.VISITORS,
    roles: [ROLES.STAFF, ROLES.RESIDENT],
    permissions: [PERMISSIONS.VISIT_VIEW, PERMISSIONS.VISIT_REGISTER],
  },
  {
    label: 'Complaints',
    icon: ICONS.COMPLAINTS,
    route: ROUTES.COMPLAINTS,
    roles: [ROLES.ADMIN, ROLES.STAFF, ROLES.RESIDENT],
    permissions: [PERMISSIONS.COMPLAINT_VIEW, PERMISSIONS.COMPLAINT_SUBMIT],
  },
  {
    label: 'Amenities',
    icon: ICONS.AMENITIES,
    route: ROUTES.AMENITIES,
    roles: [ROLES.ADMIN, ROLES.STAFF, ROLES.RESIDENT],
  },
  {
    label: 'Settings',
    icon: ICONS.SETTINGS,
    route: ROUTES.SETTINGS,
    roles: [ROLES.ADMIN, ROLES.STAFF, ROLES.RESIDENT, ROLES.ELECTRICIAN, ROLES.SECURITY],
  },
];

export const DATE_FORMATS = {
  SHORT_DATE: 'mediumDate',
  DATE_TIME: 'medium',
} as const;

const THEME = {
  STORAGE_KEY: 'lumina_theme_preference',
  DEFAULT_MODE: 'light',
  DEFAULT_COLOR: 'teal',
  DEFAULT_FONT: 'inter',
  MODE_OPTIONS: [
    { key: 'light', label: 'Light', icon: 'light_mode' },
    { key: 'dark', label: 'Dark', icon: 'dark_mode' },
    { key: 'system', label: 'System', icon: 'settings_brightness' },
  ],
  COLOR_OPTIONS: [
    { key: 'teal', label: 'Teal', value: '#0d7d6f', dark: '#0a5f54' },
    { key: 'blue', label: 'Blue', value: '#2563eb', dark: '#1d4ed8' },
    { key: 'purple', label: 'Purple', value: '#7c3aed', dark: '#6d28d9' },
    { key: 'rose', label: 'Rose', value: '#e11d48', dark: '#be123c' },
    { key: 'amber', label: 'Amber', value: '#d97706', dark: '#b45309' },
  ],
  FONT_OPTIONS: [
    { key: 'inter', label: 'Inter', value: "'Inter', sans-serif" },
    { key: 'roboto', label: 'Roboto', value: "'Roboto', sans-serif" },
    { key: 'poppins', label: 'Poppins', value: "'Poppins', sans-serif" },
  ],
} as const;

export type ThemeMode = (typeof THEME.MODE_OPTIONS)[number]['key'];

export const APP_CONSTANTS = {
  ROLES,
  ROUTES,
  ICONS,
  STATUS,
  STATUS_COLOR_KEY,
  COMPLAINT_STATUS,
  COMPLAINT_STATUS_COLOR_KEY,
  CATEGORIES,
  SENTINELS,
  STRINGS,
  NAV_ITEMS,
  DASHBOARD_VIEW,
  ACCENT,
  DATE_FORMATS,
  HTTP,
  DIALOG_WIDTHS,
  ACTIONS,
  PAGINATION,
  VALIDATION,
  THEME,
} as const;
