export const PERMISSIONS = {
  AMENITY_VIEW: 'amenity:view',
  AMENITY_MANAGE: 'amenity:manage',
  SLOT_VIEW: 'slot:view',
  SLOT_MANAGE: 'slot:manage',
  SLOT_APPLY: 'slot:apply',
  USER_VIEW: 'user:view',
  USER_MANAGE: 'user:manage',
  APPROVAL_VIEW: 'approval:view',
  APPROVAL_MANAGE: 'approval:manage',
  VIEW_ALL_FLATS: 'flat:view',
  SPECIFIC_FLATS: 'flat:self',
  VISITOR_VIEW: 'visitor:view',
  VISITOR_MANAGE: 'visitor:manage',
  VISITOR_DELETE: 'visitor:delete',
  VISIT_VIEW: 'visit:view',
  VISIT_REGISTER: 'visit:register',
  VISIT_MANAGE: 'visit:manage',
  VISIT_APPROVE: 'visit:approve',
  VISIT_CHECKIN: 'visit:checkin',
  COMPLAINT_SUBMIT: 'complaint:submit',
  COMPLAINT_VIEW: 'complaint:view',
  COMPLAINT_MANAGE: 'complaint:manage',
  COMPLAINT_CANCEL: 'complaint:cancel',
  COMPLAINT_ASSIGN: 'complaint:assign',
  COMPLAINT_COMMENT: 'complaint:comment',
  COMPLAINT_ESCALATE: 'complaint:escalate',
  STAFF_VIEW: 'staff:view',
  STAFF_MANAGE: 'staff:manage',
  STAFF_SELF_UPDATE: 'staff:self',
  STAFF_AVAILABILITY_VIEW: 'staff:availability:view',
  STAFF_AVAILABILITY_MANAGE: 'staff:availability:manage',
  REPORT_VIEW: 'report:view',
  JOB_TRIGGER: 'job:trigger',
} as const;

export const PERMISSION_LABELS: Record<string, string> = {
  [PERMISSIONS.AMENITY_VIEW]: 'View Amenities',
  [PERMISSIONS.AMENITY_MANAGE]: 'Manage Amenities',
  [PERMISSIONS.SLOT_VIEW]: 'View Slots',
  [PERMISSIONS.SLOT_MANAGE]: 'Manage Slots',
  [PERMISSIONS.SLOT_APPLY]: 'Apply for Slots',
  [PERMISSIONS.USER_VIEW]: 'View Users',
  [PERMISSIONS.USER_MANAGE]: 'Manage Users',
  [PERMISSIONS.APPROVAL_VIEW]: 'View Approvals',
  [PERMISSIONS.APPROVAL_MANAGE]: 'Manage Approvals',
  [PERMISSIONS.VIEW_ALL_FLATS]: 'View All Flats',
  [PERMISSIONS.SPECIFIC_FLATS]: 'View Own Flat',
  [PERMISSIONS.VISITOR_VIEW]: 'View Visitors',
  [PERMISSIONS.VISITOR_MANAGE]: 'Manage Visitors',
  [PERMISSIONS.VISITOR_DELETE]: 'Delete Visitors',
  [PERMISSIONS.VISIT_VIEW]: 'View Visits',
  [PERMISSIONS.VISIT_REGISTER]: 'Register Visits',
  [PERMISSIONS.VISIT_MANAGE]: 'Manage Visits',
  [PERMISSIONS.VISIT_APPROVE]: 'Approve Visits',
  [PERMISSIONS.VISIT_CHECKIN]: 'Check-in Visits',
  [PERMISSIONS.COMPLAINT_SUBMIT]: 'Submit Complaints',
  [PERMISSIONS.COMPLAINT_VIEW]: 'View Complaints',
  [PERMISSIONS.COMPLAINT_MANAGE]: 'Manage Complaints',
  [PERMISSIONS.COMPLAINT_CANCEL]: 'Cancel Complaints',
  [PERMISSIONS.COMPLAINT_ASSIGN]: 'Assign Complaints',
  [PERMISSIONS.COMPLAINT_COMMENT]: 'Comment on Complaints',
  [PERMISSIONS.COMPLAINT_ESCALATE]: 'Escalate Complaints',
  [PERMISSIONS.STAFF_VIEW]: 'View Staff',
  [PERMISSIONS.STAFF_MANAGE]: 'Manage Staff',
  [PERMISSIONS.STAFF_SELF_UPDATE]: 'Update Own Profile',
  [PERMISSIONS.STAFF_AVAILABILITY_VIEW]: 'View Staff Availability',
  [PERMISSIONS.STAFF_AVAILABILITY_MANAGE]: 'Manage Staff Availability',
  [PERMISSIONS.REPORT_VIEW]: 'View Reports',
  [PERMISSIONS.JOB_TRIGGER]: 'Trigger Jobs',
};

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
