export const VISITOR_MANAGEMENT_STRINGS = {
  PAGE_TITLE: 'Visitor Management',
  UPCOMING_TAB: 'Upcoming Visits',
  HISTORY_TAB: 'Visit History',
  BOOK_VISITOR_BUTTON: 'Book Visitor',
  SEARCH_PLACEHOLDER: 'Search by visitor name',
  STATUS_FILTER_LABEL: 'Status',
  STATUS_FILTER_ALL: 'All Statuses',
  FROM_DATE_LABEL: 'From',
  TO_DATE_LABEL: 'To',
  CLEAR_FILTERS: 'Clear Filters',
  LOADING_VISITS: 'Loading visits…',
  NO_UPCOMING_VISITS_TITLE: 'No upcoming visits',
  NO_UPCOMING_VISITS_MESSAGE: 'Visits booked for you will show up here once scheduled.',
  NO_HISTORY_VISITS_TITLE: 'No visit history yet',
  NO_HISTORY_VISITS_MESSAGE: 'Completed, rejected, or expired visits will appear here.',
  NO_RESULTS_TITLE: 'No visits match your filters',
  NO_RESULTS_MESSAGE: 'Try adjusting or clearing your filters.',
  RETRY: 'Retry',
  APPROVED_BY_LABEL: 'Approved By',
  APPROVED_ON_LABEL: 'Approved On',
  VIEW_DETAILS: 'View Details',
  RESULTS_COUNT_LABEL: 'visits found',
  UPDATE_VISITOR_TITLE: 'Update Visitor Details',
  LOADING_VISITOR: 'Loading visitor details…',
  VISITOR_LOAD_FAILED: 'Could not load visitor details. Please try again.',
  VISITOR_UPDATE_FAILED: 'Could not update visitor details. Please try again.',
  NAME_REQUIRED: 'Name is required.',
  PHONE_REQUIRED: 'Enter a valid 10-digit phone number.',
  EMAIL_INVALID: 'Enter a valid email address.',
  VISITOR_TYPE_REQUIRED: 'Please select a visitor type.',
  PURPOSE_TYPE_REQUIRED: 'Please select a purpose.',
  START_DATE_REQUIRED: 'Start date is required.',
  END_DATE_REQUIRED: 'End date is required.',
  SELECT_PLACEHOLDER: 'Select an option',
  PAGE_SIZE_LABEL: 'Per page',
  APPROVE_VISIT_TITLE: 'Approve Visit',
  APPROVE_VISIT_MESSAGE: 'Approve this visitor request?',
  VISITOR_SEARCH_MIN_CHARS_HINT: 'Keep typing to search existing visitors…',
  VISITOR_SEARCH_NO_MATCHES: 'No matching visitors — this will be booked as a new visitor.',
  VISITOR_SEARCH_FAILED: 'Could not search visitors right now.',
  EXISTING_VISITOR_SELECTED: 'Using details for an existing visitor',
  CLEAR_SELECTED_VISITOR: 'Clear and enter a new visitor',

  SECURITY_PAGE_TITLE: 'Visitor Management',
  SECURITY_PAGE_SUBTITLE: 'Select a block, then a house, to view its visits.',
  BLOCK_LABEL: 'Block',
  BLOCKS_LABEL: 'Blocks',
  HOUSES_LABEL: 'Houses',
  HOUSE_COUNT_LABEL: 'houses',
  FLAT_LABEL: 'Flat',
  BACK_TO_BLOCKS: 'Back to Blocks',
  BACK_TO_HOUSES: 'Back to Houses',
  LOADING_BLOCKS: 'Loading blocks…',
  LOADING_HOUSES: 'Loading houses…',
  BLOCKS_LOAD_FAILED: 'Could not load blocks. Please try again.',
  NO_BLOCKS_TITLE: 'No blocks found',
  NO_BLOCKS_MESSAGE: 'No residential blocks are set up yet.',
  NO_HOUSES_TITLE: 'No houses in this block',
  NO_HOUSES_MESSAGE: 'This block has no flats registered yet.',
  FLOOR_LABEL: 'Floor',
} as const;

export const VISITOR_MANAGEMENT_ICONS = {
  ADD: 'add',
  SEARCH: 'search',
  FILTER: 'tune',
  CLEAR: 'close',
  CALENDAR: 'event',
  PHONE: 'call',
  EMAIL: 'mail_outline',
  BADGE: 'badge',
  PURPOSE: 'assignment_ind',
  QR: 'qr_code_2',
  APPROVE: 'check_circle',
  REJECT: 'cancel',
  UPDATE: 'edit',
  CANCEL_VISIT: 'event_busy',
  EMPTY_UPCOMING: 'event_available',
  EMPTY_HISTORY: 'history',
  EMPTY_RESULTS: 'search_off',
  ERROR: 'error_outline',
  BACK: 'arrow_back',
  CLOSE: 'close',
  PERSON: 'person',
  REFRESH: 'refresh',
  BLOCK: 'apartment',
  HOUSE: 'home',
  CHEVRON_RIGHT: 'chevron_right',
  VERIFIED: 'verified',
} as const;

export interface StatusFilterOption {
  label: string;
  value: string;
}

export const VISIT_STATUS_FILTER_OPTIONS: Record<'UPCOMING' | 'HISTORY', StatusFilterOption[]> = {
  UPCOMING: [
    { label: 'All Statuses', value: '' },
    { label: 'Pending', value: 'PENDING' },
    { label: 'Approved', value: 'APPROVED' },
  ],
  HISTORY: [
    { label: 'All Statuses', value: '' },
    { label: 'Checked In', value: 'CHECKED_IN' },
    { label: 'Checked Out', value: 'CHECKED_OUT' },
    { label: 'Rejected', value: 'REJECTED' },
    { label: 'Expired', value: 'EXPIRED' },
    { label: 'Cancelled', value: 'CANCELLED' },
  ],
};

export const VISIT_LIST_PAGE_SIZE_OPTIONS = [6, 9, 12, 24] as const;
export const VISIT_LIST_DEFAULT_PAGE_SIZE = 12;
export const VISIT_LIST_MERGE_FETCH_LIMIT = 10;
