// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResidentVisitorService.Infrastructure.Persistence.DBContext;

#nullable disable

namespace ResidentVisitorService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DB_TEAM_C_resident_visitor")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.RefSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ref_sets");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_ref_sets_code");

                    b.ToTable("ref_sets", "DB_TEAM_C_resident_visitor");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.RefTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RefSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_set_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ref_terms");

                    b.HasIndex("RefSetId", "Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_ref_terms_ref_set_id_code");

                    b.ToTable("ref_terms", "DB_TEAM_C_resident_visitor");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_date");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FlatId")
                        .HasColumnType("uuid")
                        .HasColumnName("flat_id");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PurposeTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("purpose_type_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VisitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id")
                        .HasName("p_k_visits");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("i_x_visits_approved_by");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("i_x_visits_end_date");

                    b.HasIndex("FlatId")
                        .HasDatabaseName("i_x_visits_flat_id");

                    b.HasIndex("HostUserId")
                        .HasDatabaseName("i_x_visits_host_user_id");

                    b.HasIndex("PurposeTypeId")
                        .HasDatabaseName("i_x_visits_purpose_type_id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("i_x_visits_start_date");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("i_x_visits_status_id");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("i_x_visits_visitor_id");

                    b.ToTable("visits", "DB_TEAM_C_resident_visitor");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.VisitQrToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("p_k_visit_qr_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("i_x_visit_qr_tokens_token");

                    b.HasIndex("VisitId")
                        .IsUnique()
                        .HasDatabaseName("i_x_visit_qr_tokens_visit_id");

                    b.ToTable("visit_qr_tokens", "DB_TEAM_C_resident_visitor");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.Visitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("VisitorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitor_type_id");

                    b.HasKey("Id")
                        .HasName("p_k_visitors");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_visitors_phone_number");

                    b.HasIndex("VisitorTypeId")
                        .HasDatabaseName("i_x_visitors_visitor_type_id");

                    b.ToTable("visitors", "DB_TEAM_C_resident_visitor");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.RefTerm", b =>
                {
                    b.HasOne("ResidentVisitorService.Domain.Entities.RefSet", "RefSet")
                        .WithMany("RefTerms")
                        .HasForeignKey("RefSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_ref_terms_ref_sets_ref_set_id");

                    b.Navigation("RefSet");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.Visit", b =>
                {
                    b.HasOne("ResidentVisitorService.Domain.Entities.RefTerm", "PurposeType")
                        .WithMany("Visits")
                        .HasForeignKey("PurposeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_visits_ref_terms_purpose_type_id");

                    b.HasOne("ResidentVisitorService.Domain.Entities.RefTerm", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_visits_ref_terms_status_id");

                    b.HasOne("ResidentVisitorService.Domain.Entities.Visitor", "Visitor")
                        .WithMany("Visits")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_visits_visitors_visitor_id");

                    b.Navigation("PurposeType");

                    b.Navigation("Status");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.VisitQrToken", b =>
                {
                    b.HasOne("ResidentVisitorService.Domain.Entities.Visit", "Visit")
                        .WithOne("VisitQrToken")
                        .HasForeignKey("ResidentVisitorService.Domain.Entities.VisitQrToken", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_visit_qr_tokens_visits_visit_id");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.Visitor", b =>
                {
                    b.HasOne("ResidentVisitorService.Domain.Entities.RefTerm", "VisitorType")
                        .WithMany("Visitors")
                        .HasForeignKey("VisitorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_visitors_ref_terms_visitor_type_id");

                    b.Navigation("VisitorType");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.RefSet", b =>
                {
                    b.Navigation("RefTerms");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.RefTerm", b =>
                {
                    b.Navigation("Visitors");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.Visit", b =>
                {
                    b.Navigation("VisitQrToken");
                });

            modelBuilder.Entity("ResidentVisitorService.Domain.Entities.Visitor", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
