// <auto-generated />
using System;
using ComplaintMaintenanceService.Infrastructure.Persistence.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComplaintMaintenanceService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618162900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DB_TEAM_C_complaint")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.AutoAssignmentRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowResidentTimePick")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_resident_time_pick");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("FallbackStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("fallback_staff_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PriorityId")
                        .HasColumnType("uuid")
                        .HasColumnName("priority_id");

                    b.Property<int>("ServiceDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("service_duration_minutes");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<TimeSpan?>("TimeWindowEnd")
                        .HasColumnType("interval")
                        .HasColumnName("time_window_end");

                    b.Property<TimeSpan?>("TimeWindowStart")
                        .HasColumnType("interval")
                        .HasColumnName("time_window_start");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_auto_assignment_rules");

                    b.HasIndex("FallbackStaffId")
                        .HasDatabaseName("i_x_auto_assignment_rules_fallback_staff_id");

                    b.HasIndex("PriorityId")
                        .HasDatabaseName("i_x_auto_assignment_rules_priority_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("i_x_auto_assignment_rules_staff_id");

                    b.HasIndex("CategoryId", "PriorityId")
                        .IsUnique()
                        .HasDatabaseName("i_x_auto_assignment_rules_category_id_priority_id");

                    b.ToTable("auto_assignment_rules", "DB_TEAM_C_complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_categories_name");

                    b.ToTable("categories", "DB_TEAM_C_complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("ComplaintTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("complaint_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PriorityId")
                        .HasColumnType("uuid")
                        .HasColumnName("priority_id");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_date");

                    b.Property<Guid?>("ScheduledSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduled_slot_id");

                    b.Property<TimeSpan?>("ScheduledTime")
                        .HasColumnType("interval")
                        .HasColumnName("scheduled_time");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_complaints");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("i_x_complaints_category_id");

                    b.HasIndex("ComplaintTypeId")
                        .HasDatabaseName("i_x_complaints_complaint_type_id");

                    b.HasIndex("PriorityId")
                        .HasDatabaseName("i_x_complaints_priority_id");

                    b.HasIndex("ScheduledSlotId")
                        .HasDatabaseName("i_x_complaints_scheduled_slot_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("i_x_complaints_status_id");

                    b.ToTable("complaints", "DB_TEAM_C_complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.ComplaintAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_date");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_date");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid")
                        .HasColumnName("complaint_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DenialReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("denial_reason");

                    b.Property<DateTime?>("DeniedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("denied_date");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_complaint_assignments");

                    b.HasIndex("ComplaintId")
                        .HasDatabaseName("i_x_complaint_assignments_complaint_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("i_x_complaint_assignments_staff_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("i_x_complaint_assignments_status_id");

                    b.ToTable("complaint_assignments", "DB_TEAM_C_complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.ComplaintComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment_text");

                    b.Property<Guid>("CommentedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("commented_by");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid")
                        .HasColumnName("complaint_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("StaffRating")
                        .HasColumnType("integer")
                        .HasColumnName("staff_rating");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_complaint_comments");

                    b.HasIndex("ComplaintId")
                        .HasDatabaseName("i_x_complaint_comments_complaint_id");

                    b.ToTable("complaint_comments", "DB_TEAM_C_complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.ComplaintEscalation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid")
                        .HasColumnName("complaint_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("EscalatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("escalated_by");

                    b.Property<Guid>("EscalatedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("escalated_to");

                    b.Property<DateTime>("EscalationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalation_date");

                    b.Property<string>("EscalationReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("escalation_reason");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolution_date");

                    b.Property<bool>("ResolvedAfterEscalation")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved_after_escalation");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_complaint_escalations");

                    b.HasIndex("ComplaintId")
                        .HasDatabaseName("i_x_complaint_escalations_complaint_id");

                    b.ToTable("complaint_escalations", "DB_TEAM_C_complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.ComplaintProgressLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_date");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid")
                        .HasColumnName("complaint_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("remarks");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_complaint_progress_logs");

                    b.HasIndex("ComplaintId")
                        .HasDatabaseName("i_x_complaint_progress_logs_complaint_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("i_x_complaint_progress_logs_status_id");

                    b.ToTable("complaint_progress_logs", "DB_TEAM_C_complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.RefSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ref_sets");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_ref_sets_code");

                    b.ToTable("ref_sets", "DB_TEAM_C_complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.RefTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RefSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_set_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_ref_terms");

                    b.HasIndex("RefSetId", "Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_ref_terms_ref_set_id_code");

                    b.ToTable("ref_terms", "DB_TEAM_C_complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("details");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_staff");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("i_x_staff_category_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_staff_user_id");

                    b.ToTable("staff", "DB_TEAM_C_complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.StaffAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AvailableDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_date");

                    b.Property<Guid?>("ComplaintId")
                        .HasColumnType("uuid")
                        .HasColumnName("complaint_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_booked");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cancelled");

                    b.Property<TimeSpan>("SlotEndTime")
                        .HasColumnType("interval")
                        .HasColumnName("slot_end_time");

                    b.Property<TimeSpan>("SlotStartTime")
                        .HasColumnType("interval")
                        .HasColumnName("slot_start_time");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_staff_availabilities");

                    b.HasIndex("ComplaintId")
                        .HasDatabaseName("i_x_staff_availabilities_complaint_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("i_x_staff_availabilities_staff_id");

                    b.ToTable("staff_availabilities", "DB_TEAM_C_complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.AutoAssignmentRule", b =>
                {
                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Category", "Category")
                        .WithMany("AutoAssignmentRules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_auto_assignment_rules_categories_category_id");

                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Staff", "FallbackStaff")
                        .WithMany()
                        .HasForeignKey("FallbackStaffId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_auto_assignment_rules_staff_fallback_staff_id");

                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.RefTerm", "Priority")
                        .WithMany("AutoAssignmentRules")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_auto_assignment_rules_ref_terms_priority_id");

                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Staff", "Staff")
                        .WithMany("AutoAssignmentRules")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_auto_assignment_rules_staff_staff_id");

                    b.Navigation("Category");

                    b.Navigation("FallbackStaff");

                    b.Navigation("Priority");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.Complaint", b =>
                {
                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Category", "Category")
                        .WithMany("Complaints")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_complaints_categories_category_id");

                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.RefTerm", "ComplaintType")
                        .WithMany("Complaints")
                        .HasForeignKey("ComplaintTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_complaints_ref_terms_complaint_type_id");

                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.RefTerm", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_complaints_ref_terms_priority_id");

                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.StaffAvailability", "ScheduledSlot")
                        .WithMany()
                        .HasForeignKey("ScheduledSlotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_complaints_staff_availabilities_scheduled_slot_id");

                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.RefTerm", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_complaints_ref_terms_status_id");

                    b.Navigation("Category");

                    b.Navigation("ComplaintType");

                    b.Navigation("Priority");

                    b.Navigation("ScheduledSlot");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.ComplaintAssignment", b =>
                {
                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Complaint", "Complaint")
                        .WithMany("ComplaintAssignments")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_complaint_assignments_complaints_complaint_id");

                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Staff", "Staff")
                        .WithMany("ComplaintAssignments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_complaint_assignments_staff_staff_id");

                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.RefTerm", "Status")
                        .WithMany("ComplaintAssignments")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_complaint_assignments_ref_terms_status_id");

                    b.Navigation("Complaint");

                    b.Navigation("Staff");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.ComplaintComment", b =>
                {
                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Complaint", "Complaint")
                        .WithMany("ComplaintComments")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_complaint_comments_complaints_complaint_id");

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.ComplaintEscalation", b =>
                {
                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Complaint", "Complaint")
                        .WithMany("ComplaintEscalations")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_complaint_escalations_complaints_complaint_id");

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.ComplaintProgressLog", b =>
                {
                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Complaint", "Complaint")
                        .WithMany("ComplaintProgressLogs")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_complaint_progress_logs_complaints_complaint_id");

                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.RefTerm", "Status")
                        .WithMany("ComplaintProgressLogs")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_complaint_progress_logs_ref_terms_status_id");

                    b.Navigation("Complaint");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.RefTerm", b =>
                {
                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.RefSet", "RefSet")
                        .WithMany("RefTerms")
                        .HasForeignKey("RefSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_ref_terms_ref_sets_ref_set_id");

                    b.Navigation("RefSet");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.Staff", b =>
                {
                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Category", "Category")
                        .WithMany("Staff")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_staff_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.StaffAvailability", b =>
                {
                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Complaint", "Complaint")
                        .WithMany()
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_staff_availabilities_complaints_complaint_id");

                    b.HasOne("ComplaintMaintenanceService.Domain.Entities.Staff", "Staff")
                        .WithMany("StaffAvailabilities")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_staff_availabilities_staff_staff_id");

                    b.Navigation("Complaint");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.Category", b =>
                {
                    b.Navigation("AutoAssignmentRules");

                    b.Navigation("Complaints");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.Complaint", b =>
                {
                    b.Navigation("ComplaintAssignments");

                    b.Navigation("ComplaintComments");

                    b.Navigation("ComplaintEscalations");

                    b.Navigation("ComplaintProgressLogs");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.RefSet", b =>
                {
                    b.Navigation("RefTerms");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.RefTerm", b =>
                {
                    b.Navigation("AutoAssignmentRules");

                    b.Navigation("ComplaintAssignments");

                    b.Navigation("ComplaintProgressLogs");

                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("ComplaintMaintenanceService.Domain.Entities.Staff", b =>
                {
                    b.Navigation("AutoAssignmentRules");

                    b.Navigation("ComplaintAssignments");

                    b.Navigation("StaffAvailabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
